language: python
python:
  - "2.6"
# command to install dependencies
install:
  - "pip install redis"
  - "pip install unittest2"
# databases
services:
  - redis-server
# command to run tests
script: nosetests
